params:
  left_delim: "{{"
  right_delim: "}}"

nats:
  url: '{{ env "NATS_URL" }}'
  token_bounds:
    min: 1m
    max: 24h

service:
  name: '{{ env "IAM_NAME" }}'
  version: '{{ env "IAM_VERSION" }}'
  description: '{{ env "IAM_DESCRIPTION" }}'
  creds_file: '{{ env "IAM_USER_CREDS" }}'

  account:
    name: '{{ env "IAM_ACCOUNT_NAME" }}'
    signing_nkey: '{{ readFile "$IAM_ACCOUNT_SIGNK" }}'
    encryption:
      enabled: true
      xkey_secret: '{{ readNthLine 1 (env "IAM_SERVICE_XK") }}'
