apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nats-iam-broker.fullname" . }}-rbac-accounts
  labels: {{- include "nats-iam-broker.labels" . | nindent 4 }}
data:
  rbac-accounts.yaml: |
    rbac:
      token_max_expiration: {{ .Values.config.rbac.tokenMaxExpiration }}
      user_accounts:
      {{- range .Values.config.rbac.accounts }}
        - name: {{ .name }}
          public_key: {{ include "secretValue" (list .publicKey.type .publicKey.value ) }}
          signing_nkey: {{ include "secretValue" (list .signingNkey.type .signingNkey.value ) }}
      {{- end }}
      {{- if .Values.vault.enabled }}
      {{- range .Values.vault.rbacCredentials }}
        - name: {{ .name }}
          public_key: {{ include "secretValue" (list "file" (printf "/vault/secrets/rbac/%s/a-identity.pub" .name)) }}
          signing_nkey: {{ include "secretValue" (list "file" (printf "/vault/secrets/rbac/%s/a-sign.nk" .name))  }}
      {{- end }}
      {{- end }}
