apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nats-iam-broker.fullname" . }}-rbac
  labels: {{- include "nats-iam-broker.labels" . | nindent 4 }}
data:
  40-rbac.yaml: |
    rbac:
      {{- with .Values.app.rbac }}
      {{- toYaml . | nindent 6 }}
      {{- end}}
