apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nats-iam-broker.fullname" . }}-app
  labels: {{- include "nats-iam-broker.labels" . | nindent 4 }}
data:
  app.yaml: |
    {{- with .Values.config.params }}
    params:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    nats:
      url: {{ .Values.config.app.nats.url }}
      token_bounds:
        min: {{ .Values.config.app.nats.jwtExpiry.min }}
        max: {{ .Values.config.app.nats.jwtExpiry.max }}

    service:
      name: {{ .Values.config.app.name }}
      version: {{ include "getImageTag" . }}
      description: {{ .Values.config.app.description }}
      creds_file: {{ .Values.config.app.natsMicroService.userCredsFile }}

      account:
        name: {{ .Values.config.app.natsMicroService.account.name }}
        {{- with .Values.config.app.natsMicroService.account.signingNkey }}
        signing_nkey: {{ include "secretValue" (list .type .value) }}
        {{- end }}

        encryption:
          enabled: {{ .Values.config.app.natsMicroService.encryption.enabled }}
          {{- with .Values.config.app.natsMicroService.encryption.xkeySecret }}
          xkey_secret: {{ include "secretValue" (list .type .value) }}
          {{- end }}
