apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nats-iam-broker.fullname" . }}
  labels:
    {{- include "nats-iam-broker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nats-iam-broker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nats-iam-broker.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nats-iam-broker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.devDebug }}
          command: 
            - sleep
          args:
            - infinity
          {{- else }}
          args:
            - -log={{ .Values.logging.level }}
{{- if not .Values.logging.json }}
            - -log-human
{{- end }}
          {{- end }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: volume-config-rbac
              mountPath: /config/40-rbac.yaml
              subPath: 40-rbac.yaml
              readOnly: true
            {{- if .Values.volumeMounts }}
            {{ toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
      volumes:
        - name: volume-config-rbac
          configMap:
            name: {{ include "nats-iam-broker.fullname" . }}-rbac
        {{- if .Values.volumes }}
        {{ toYaml .Values.volumes | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
