{{- if and .Values.server.metrics .Values.server.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nats-iam-broker.fullname" . }}
  labels:
    {{- include "nats-iam-broker.labels" . | nindent 4 }}
    {{- with .Values.server.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "nats-iam-broker.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.server.serviceMonitor.interval }}
      path: /metrics
{{- end }}
