ARG OIDC_SERVER_ARCH
# https://github.com/vdbulcke/oidc-server-demo/releases
ARG OIDC_SERVER_VERSION=v0.9.0
ARG GOVERSION=1.24

FROM golang:${GOVERSION}-alpine AS builder

ARG BUILD_ARCH
ARG BUILD_OS

RUN apk update && apk add --no-cache git bash curl jq make 

# https://github.com/nats-io/nats-server/releases
RUN go install github.com/nats-io/nats-server/v2@v2.12.2

# https://github.com/nats-io/natscli/releases
RUN go install github.com/nats-io/natscli/nats@v0.3.0

# https://github.com/nats-io/nsc/releases
RUN go install github.com/nats-io/nsc/v2@v2.12.0

WORKDIR /usr/src/app

# pre-download all dependencies once for faster builds
COPY go.sum go.mod ./
RUN go mod download

COPY . .

RUN make build && \
    ln -s /usr/src/app/build/nats-iam-broker-${BUILD_OS}-${BUILD_ARCH} /usr/local/bin/nats-iam-broker && \
    ln -s /usr/src/app/build/test-client-${BUILD_OS}-${BUILD_ARCH} /usr/local/bin/test-client


FROM ghcr.io/vdbulcke/oidc-server:${OIDC_SERVER_VERSION}${OIDC_SERVER_ARCH} as oidc_server


# minimal container
FROM alpine:3

LABEL org.opencontainers.image.source="https://github.com/jr200/nats-iam-broker"
LABEL org.opencontainers.image.description="nats-iam-broker runtime stage"

RUN apk add --no-cache bash curl jq && \
    apk add --no-cache --update ca-certificates socat

WORKDIR /usr/src/app

COPY --from=builder /usr/local/bin/nats-iam-broker /usr/local/bin/nats-iam-broker
COPY --from=builder /usr/local/bin/test-client /usr/local/bin/test-client

COPY --from=oidc_server /app/oidc-server /usr/local/bin/oidc-server
COPY ./docker/oidc-server/config.yaml /usr/src/app/oidc-server/config.yaml
COPY ./docker/debug.sh /bin/debug.sh
COPY ./docker/docker-entrypoint.sh /docker-entrypoint.sh

# for example programs
COPY --from=builder /go/bin/nsc /bin/nsc
COPY --from=builder /go/bin/nats /bin/nats
COPY --from=builder /go/bin/nats-server /bin/nats-server
COPY --from=builder /usr/src/app/configs /usr/src/app/configs
COPY --from=builder /usr/src/app/examples /usr/src/app/examples
COPY --from=builder /usr/src/app/scripts /usr/src/app/scripts

ENTRYPOINT ["/bin/debug.sh"]

CMD ["shell"]