idp:
  - description: oidctest-private
    client_id: private
    issuer_url: https://oidctest.wsweet.org/

    validation:
      token_bounds:
        min: 1m0s
        max: 2h
      claims:
        - aud
        - iat
        - exp
        - sub
      aud:
        - private

  - description: random-ununused-item
    client_id: random
    issuer_url: https://oidctest.wsweet.org/

    validation:
      claims:
        - aud
        - iat
        - exp
        - sub
      aud:
        - random-aud

  - description: "My Secondary IDP (can sometimes be unavailable)"
    issuer_url: "https://secondary-idp.internal:8443/"
    client_id: "secondary-client"
    ignore_setup_error: true # <<< Set this to true to block it from halting startup if it's unavailable
    validation:
      aud: ["secondary-aud"]

  - description: "Development IDP (ignore if misconfigured)"
    issuer_url: "http://localhost:8080/auth/realms/dev"
    client_id: "dev-client"
    ignore_setup_error: true # <<< Also ignore errors for this one when it is misconfigured
    validation:
      skip_audience_validation: true
