name: ci-go

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  ci:
    uses: jr200-labs/github-action-templates/.github/workflows/ci_go.yaml@master
