name: ci

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  ci:
    uses: jr200-labs/github-action-templates/.github/workflows/ci_go.yaml@master

  commitlint:
    uses: jr200-labs/github-action-templates/.github/workflows/lint_commits.yaml@master
    with:
      runner: ${{ fromJSON(vars.RUNNER_PROFILES)[vars.RUNNER_PROFILE].default }}
